replicaCount: 1

image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

config:
  POSTGRES_DB: "platformiq_demo"

secret:
  POSTGRES_USER: "platformiq"
  POSTGRES_PASSWORD: "platformiq_password"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
