apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  labels:
    app: payment-service
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
