apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  labels:
    app: payment-service
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
