apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/shounakdev/pipeline-iq.git
    targetRevision: sprint-3
    path: infrastructure/helm/payment-service
    helm:
      valueFiles:
        - ../../gitops/environments/staging/payment-service-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: platformiq-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
