replicaCount: 1

image:
  repository: platformiq/order-service
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

env:
  SPRING_PROFILES_ACTIVE: "kubernetes"

secret:
  enabled: false
  data: {}

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  livenessPath: /health
  readinessPath: /ready
