replicaCount: 1

image:
  repository: platformiq/order-service
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

env:
  INVENTORY_SERVICE_URL: "http://inventory-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8080"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
