replicaCount: 1

image:
  repository: platformiq/payment-service
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30082

env:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/platformiq_demo"
  SIMULATE_PAYMENT_FAILURE: "false"
  SIMULATE_DATABASE_TIMEOUT: "false"
  SIMULATE_HIGH_LATENCY: "false"
  SIMULATE_RANDOM_500: "false"

secret:
  enabled: true
  data:
    SPRING_DATASOURCE_USERNAME: "platformiq"
    SPRING_DATASOURCE_PASSWORD: "platformiq_password"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  livenessPath: /health
  readinessPath: /ready
